// Code generated by protoc-gen-go. DO NOT EDIT.
// source: activity.proto

package activityPb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserActivityProcessRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId           int32    `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserActivityProcessRequest) Reset()         { *m = GetUserActivityProcessRequest{} }
func (m *GetUserActivityProcessRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserActivityProcessRequest) ProtoMessage()    {}
func (*GetUserActivityProcessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{0}
}

func (m *GetUserActivityProcessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserActivityProcessRequest.Unmarshal(m, b)
}
func (m *GetUserActivityProcessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserActivityProcessRequest.Marshal(b, m, deterministic)
}
func (m *GetUserActivityProcessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserActivityProcessRequest.Merge(m, src)
}
func (m *GetUserActivityProcessRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserActivityProcessRequest.Size(m)
}
func (m *GetUserActivityProcessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserActivityProcessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserActivityProcessRequest proto.InternalMessageInfo

func (m *GetUserActivityProcessRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserActivityProcessRequest) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

type GetUserActivityProcessResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId           int32    `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	JointConfig          []byte   `protobuf:"bytes,4,opt,name=joint_config,json=jointConfig,proto3" json:"joint_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserActivityProcessResponse) Reset()         { *m = GetUserActivityProcessResponse{} }
func (m *GetUserActivityProcessResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserActivityProcessResponse) ProtoMessage()    {}
func (*GetUserActivityProcessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{1}
}

func (m *GetUserActivityProcessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserActivityProcessResponse.Unmarshal(m, b)
}
func (m *GetUserActivityProcessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserActivityProcessResponse.Marshal(b, m, deterministic)
}
func (m *GetUserActivityProcessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserActivityProcessResponse.Merge(m, src)
}
func (m *GetUserActivityProcessResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserActivityProcessResponse.Size(m)
}
func (m *GetUserActivityProcessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserActivityProcessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserActivityProcessResponse proto.InternalMessageInfo

func (m *GetUserActivityProcessResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserActivityProcessResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserActivityProcessResponse) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *GetUserActivityProcessResponse) GetJointConfig() []byte {
	if m != nil {
		return m.JointConfig
	}
	return nil
}

type UpdateUserActivityProcessRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId           int32    `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	JointConfig          []byte   `protobuf:"bytes,4,opt,name=joint_config,json=jointConfig,proto3" json:"joint_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserActivityProcessRequest) Reset()         { *m = UpdateUserActivityProcessRequest{} }
func (m *UpdateUserActivityProcessRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserActivityProcessRequest) ProtoMessage()    {}
func (*UpdateUserActivityProcessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{2}
}

func (m *UpdateUserActivityProcessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserActivityProcessRequest.Unmarshal(m, b)
}
func (m *UpdateUserActivityProcessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserActivityProcessRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserActivityProcessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserActivityProcessRequest.Merge(m, src)
}
func (m *UpdateUserActivityProcessRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserActivityProcessRequest.Size(m)
}
func (m *UpdateUserActivityProcessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserActivityProcessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserActivityProcessRequest proto.InternalMessageInfo

func (m *UpdateUserActivityProcessRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateUserActivityProcessRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateUserActivityProcessRequest) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *UpdateUserActivityProcessRequest) GetJointConfig() []byte {
	if m != nil {
		return m.JointConfig
	}
	return nil
}

type UpdateUserActivityProcessResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserActivityProcessResponse) Reset()         { *m = UpdateUserActivityProcessResponse{} }
func (m *UpdateUserActivityProcessResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserActivityProcessResponse) ProtoMessage()    {}
func (*UpdateUserActivityProcessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{3}
}

func (m *UpdateUserActivityProcessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserActivityProcessResponse.Unmarshal(m, b)
}
func (m *UpdateUserActivityProcessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserActivityProcessResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserActivityProcessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserActivityProcessResponse.Merge(m, src)
}
func (m *UpdateUserActivityProcessResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserActivityProcessResponse.Size(m)
}
func (m *UpdateUserActivityProcessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserActivityProcessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserActivityProcessResponse proto.InternalMessageInfo

func (m *UpdateUserActivityProcessResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetActivityConfigRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActivityConfigRequest) Reset()         { *m = GetActivityConfigRequest{} }
func (m *GetActivityConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetActivityConfigRequest) ProtoMessage()    {}
func (*GetActivityConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{4}
}

func (m *GetActivityConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActivityConfigRequest.Unmarshal(m, b)
}
func (m *GetActivityConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActivityConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetActivityConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActivityConfigRequest.Merge(m, src)
}
func (m *GetActivityConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetActivityConfigRequest.Size(m)
}
func (m *GetActivityConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActivityConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActivityConfigRequest proto.InternalMessageInfo

func (m *GetActivityConfigRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetActivityConfigResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State                int32    `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	AwardConfig          []byte   `protobuf:"bytes,3,opt,name=award_config,json=awardConfig,proto3" json:"award_config,omitempty"`
	OpenConfig           []byte   `protobuf:"bytes,4,opt,name=open_config,json=openConfig,proto3" json:"open_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActivityConfigResponse) Reset()         { *m = GetActivityConfigResponse{} }
func (m *GetActivityConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetActivityConfigResponse) ProtoMessage()    {}
func (*GetActivityConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{5}
}

func (m *GetActivityConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActivityConfigResponse.Unmarshal(m, b)
}
func (m *GetActivityConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActivityConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetActivityConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActivityConfigResponse.Merge(m, src)
}
func (m *GetActivityConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetActivityConfigResponse.Size(m)
}
func (m *GetActivityConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActivityConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetActivityConfigResponse proto.InternalMessageInfo

func (m *GetActivityConfigResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetActivityConfigResponse) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *GetActivityConfigResponse) GetAwardConfig() []byte {
	if m != nil {
		return m.AwardConfig
	}
	return nil
}

func (m *GetActivityConfigResponse) GetOpenConfig() []byte {
	if m != nil {
		return m.OpenConfig
	}
	return nil
}

type UpdateActivityConfigRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State                int32    `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	AwardConfig          []byte   `protobuf:"bytes,3,opt,name=award_config,json=awardConfig,proto3" json:"award_config,omitempty"`
	OpenConfig           []byte   `protobuf:"bytes,4,opt,name=open_config,json=openConfig,proto3" json:"open_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateActivityConfigRequest) Reset()         { *m = UpdateActivityConfigRequest{} }
func (m *UpdateActivityConfigRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateActivityConfigRequest) ProtoMessage()    {}
func (*UpdateActivityConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{6}
}

func (m *UpdateActivityConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateActivityConfigRequest.Unmarshal(m, b)
}
func (m *UpdateActivityConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateActivityConfigRequest.Marshal(b, m, deterministic)
}
func (m *UpdateActivityConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateActivityConfigRequest.Merge(m, src)
}
func (m *UpdateActivityConfigRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateActivityConfigRequest.Size(m)
}
func (m *UpdateActivityConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateActivityConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateActivityConfigRequest proto.InternalMessageInfo

func (m *UpdateActivityConfigRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateActivityConfigRequest) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *UpdateActivityConfigRequest) GetAwardConfig() []byte {
	if m != nil {
		return m.AwardConfig
	}
	return nil
}

func (m *UpdateActivityConfigRequest) GetOpenConfig() []byte {
	if m != nil {
		return m.OpenConfig
	}
	return nil
}

type UpdateActivityConfigResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateActivityConfigResponse) Reset()         { *m = UpdateActivityConfigResponse{} }
func (m *UpdateActivityConfigResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateActivityConfigResponse) ProtoMessage()    {}
func (*UpdateActivityConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a684c9a0549e7832, []int{7}
}

func (m *UpdateActivityConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateActivityConfigResponse.Unmarshal(m, b)
}
func (m *UpdateActivityConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateActivityConfigResponse.Marshal(b, m, deterministic)
}
func (m *UpdateActivityConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateActivityConfigResponse.Merge(m, src)
}
func (m *UpdateActivityConfigResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateActivityConfigResponse.Size(m)
}
func (m *UpdateActivityConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateActivityConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateActivityConfigResponse proto.InternalMessageInfo

func (m *UpdateActivityConfigResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserActivityProcessRequest)(nil), "activityPb.GetUserActivityProcessRequest")
	proto.RegisterType((*GetUserActivityProcessResponse)(nil), "activityPb.GetUserActivityProcessResponse")
	proto.RegisterType((*UpdateUserActivityProcessRequest)(nil), "activityPb.UpdateUserActivityProcessRequest")
	proto.RegisterType((*UpdateUserActivityProcessResponse)(nil), "activityPb.UpdateUserActivityProcessResponse")
	proto.RegisterType((*GetActivityConfigRequest)(nil), "activityPb.GetActivityConfigRequest")
	proto.RegisterType((*GetActivityConfigResponse)(nil), "activityPb.GetActivityConfigResponse")
	proto.RegisterType((*UpdateActivityConfigRequest)(nil), "activityPb.UpdateActivityConfigRequest")
	proto.RegisterType((*UpdateActivityConfigResponse)(nil), "activityPb.UpdateActivityConfigResponse")
}

func init() { proto.RegisterFile("activity.proto", fileDescriptor_a684c9a0549e7832) }

var fileDescriptor_a684c9a0549e7832 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcd, 0x4f, 0xea, 0x40,
	0x10, 0x7f, 0x2d, 0x0f, 0xc8, 0x1b, 0x08, 0x2f, 0x6e, 0x88, 0x16, 0xfc, 0x82, 0x46, 0x23, 0x12,
	0xe5, 0xa0, 0x17, 0x2f, 0x1e, 0x8c, 0x07, 0xc2, 0xcd, 0xd4, 0x70, 0xf0, 0x44, 0x4a, 0x3b, 0x92,
	0xd5, 0xd8, 0x2d, 0xdd, 0x05, 0xa3, 0x77, 0xe3, 0xc9, 0xf8, 0xb7, 0xf9, 0x1f, 0x99, 0xb6, 0x6c,
	0x45, 0xe8, 0x07, 0x17, 0x3d, 0xce, 0xec, 0xec, 0xef, 0x63, 0x66, 0x76, 0xa1, 0x62, 0x5a, 0x82,
	0x4e, 0xa9, 0x78, 0xea, 0xb8, 0x1e, 0x13, 0x8c, 0x80, 0x8c, 0xaf, 0x86, 0xfa, 0x0d, 0x6c, 0x77,
	0x51, 0xf4, 0x39, 0x7a, 0x17, 0x32, 0xe9, 0x31, 0x0b, 0x39, 0x37, 0x70, 0x3c, 0x41, 0x2e, 0xc8,
	0x06, 0x14, 0x27, 0x1c, 0xbd, 0x01, 0xb5, 0x35, 0xa5, 0xa1, 0xb4, 0xf2, 0x46, 0xc1, 0x0f, 0x7b,
	0x36, 0xd9, 0x85, 0x92, 0xc4, 0xf1, 0x0f, 0xd5, 0xe0, 0x30, 0x82, 0xee, 0xd9, 0xfa, 0x9b, 0x02,
	0x3b, 0x49, 0xd8, 0xdc, 0x65, 0x0e, 0x47, 0x52, 0x01, 0x35, 0xc2, 0x55, 0xa9, 0x3d, 0x4f, 0xa6,
	0xa6, 0x91, 0xe5, 0x16, 0xc9, 0x48, 0x13, 0xca, 0x77, 0x8c, 0x3a, 0x62, 0x60, 0x31, 0xe7, 0x96,
	0x8e, 0xb4, 0xbf, 0x0d, 0xa5, 0x55, 0x36, 0x4a, 0x41, 0xee, 0x32, 0x48, 0xe9, 0xef, 0x0a, 0x34,
	0xfa, 0xae, 0x6d, 0x0a, 0x4c, 0xb1, 0xfb, 0xab, 0x8a, 0xce, 0xa1, 0x99, 0x22, 0x68, 0xd6, 0x23,
	0x0d, 0x8a, 0x0f, 0xc8, 0xb9, 0x39, 0xc2, 0x40, 0xd6, 0x3f, 0x43, 0x86, 0x7a, 0x1b, 0xb4, 0x2e,
	0x0a, 0x79, 0x2f, 0xc4, 0x4c, 0xf0, 0xa1, 0xbf, 0x28, 0x50, 0x8b, 0x29, 0x4e, 0x98, 0x43, 0x15,
	0xf2, 0x5c, 0x98, 0x02, 0x67, 0x9e, 0xc3, 0xc0, 0x77, 0x64, 0x3e, 0x9a, 0x9e, 0x2d, 0x1d, 0xe5,
	0x42, 0x47, 0x41, 0x2e, 0x04, 0xf4, 0xbb, 0xc2, 0x5c, 0x74, 0xbe, 0x7b, 0x06, 0x3f, 0x35, 0xb3,
	0xfc, 0xaa, 0xc0, 0x66, 0xe8, 0x79, 0x25, 0xdd, 0x3f, 0xa8, 0xe4, 0x0c, 0xb6, 0xe2, 0x85, 0x64,
	0xf5, 0xfd, 0xe4, 0x23, 0x07, 0xff, 0xe5, 0xa5, 0x6b, 0xf4, 0xa6, 0xd4, 0x42, 0x32, 0x86, 0xf5,
	0xf8, 0x5d, 0x27, 0x87, 0x9d, 0xaf, 0xe7, 0xd6, 0x49, 0x7d, 0x6b, 0xf5, 0xf6, 0x2a, 0xa5, 0xa1,
	0x3c, 0xfd, 0x0f, 0x79, 0x86, 0x5a, 0xe2, 0xf6, 0x90, 0xa3, 0x79, 0xa8, 0xac, 0xad, 0xaf, 0x1f,
	0xaf, 0x58, 0x1d, 0x71, 0x0f, 0x61, 0x6d, 0x69, 0x9b, 0xc8, 0xde, 0x82, 0xfc, 0xd8, 0x09, 0xd7,
	0xf7, 0x33, 0xaa, 0x22, 0x8e, 0x7b, 0xa8, 0xc6, 0x0d, 0x88, 0x1c, 0x2c, 0x8b, 0x8d, 0x67, 0x6a,
	0x65, 0x17, 0x4a, 0xb2, 0x61, 0x21, 0xf8, 0x1a, 0x4f, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x67,
	0x58, 0x6e, 0xdc, 0x2c, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActivityServiceClient is the client API for ActivityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActivityServiceClient interface {
	// 拉取用户进度
	// 拉取时，不存在时新增，存在但过期时，更新至最新再拉取，存在切未过去，则拉取正常
	GetUserActivityProcess(ctx context.Context, in *GetUserActivityProcessRequest, opts ...grpc.CallOption) (*GetUserActivityProcessResponse, error)
	// 更新用户进度
	UpdateUserActivityProcess(ctx context.Context, in *UpdateUserActivityProcessRequest, opts ...grpc.CallOption) (*UpdateUserActivityProcessResponse, error)
	// 获取活动配置
	GetActivityConfig(ctx context.Context, in *GetActivityConfigRequest, opts ...grpc.CallOption) (*GetActivityConfigResponse, error)
	// 更新活动配置
	UpdateActivityConfig(ctx context.Context, in *UpdateActivityConfigRequest, opts ...grpc.CallOption) (*UpdateActivityConfigResponse, error)
}

type activityServiceClient struct {
	cc *grpc.ClientConn
}

func NewActivityServiceClient(cc *grpc.ClientConn) ActivityServiceClient {
	return &activityServiceClient{cc}
}

func (c *activityServiceClient) GetUserActivityProcess(ctx context.Context, in *GetUserActivityProcessRequest, opts ...grpc.CallOption) (*GetUserActivityProcessResponse, error) {
	out := new(GetUserActivityProcessResponse)
	err := c.cc.Invoke(ctx, "/activityPb.ActivityService/GetUserActivityProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) UpdateUserActivityProcess(ctx context.Context, in *UpdateUserActivityProcessRequest, opts ...grpc.CallOption) (*UpdateUserActivityProcessResponse, error) {
	out := new(UpdateUserActivityProcessResponse)
	err := c.cc.Invoke(ctx, "/activityPb.ActivityService/UpdateUserActivityProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) GetActivityConfig(ctx context.Context, in *GetActivityConfigRequest, opts ...grpc.CallOption) (*GetActivityConfigResponse, error) {
	out := new(GetActivityConfigResponse)
	err := c.cc.Invoke(ctx, "/activityPb.ActivityService/GetActivityConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) UpdateActivityConfig(ctx context.Context, in *UpdateActivityConfigRequest, opts ...grpc.CallOption) (*UpdateActivityConfigResponse, error) {
	out := new(UpdateActivityConfigResponse)
	err := c.cc.Invoke(ctx, "/activityPb.ActivityService/UpdateActivityConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServiceServer is the server API for ActivityService service.
type ActivityServiceServer interface {
	// 拉取用户进度
	// 拉取时，不存在时新增，存在但过期时，更新至最新再拉取，存在切未过去，则拉取正常
	GetUserActivityProcess(context.Context, *GetUserActivityProcessRequest) (*GetUserActivityProcessResponse, error)
	// 更新用户进度
	UpdateUserActivityProcess(context.Context, *UpdateUserActivityProcessRequest) (*UpdateUserActivityProcessResponse, error)
	// 获取活动配置
	GetActivityConfig(context.Context, *GetActivityConfigRequest) (*GetActivityConfigResponse, error)
	// 更新活动配置
	UpdateActivityConfig(context.Context, *UpdateActivityConfigRequest) (*UpdateActivityConfigResponse, error)
}

// UnimplementedActivityServiceServer can be embedded to have forward compatible implementations.
type UnimplementedActivityServiceServer struct {
}

func (*UnimplementedActivityServiceServer) GetUserActivityProcess(ctx context.Context, req *GetUserActivityProcessRequest) (*GetUserActivityProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserActivityProcess not implemented")
}
func (*UnimplementedActivityServiceServer) UpdateUserActivityProcess(ctx context.Context, req *UpdateUserActivityProcessRequest) (*UpdateUserActivityProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserActivityProcess not implemented")
}
func (*UnimplementedActivityServiceServer) GetActivityConfig(ctx context.Context, req *GetActivityConfigRequest) (*GetActivityConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivityConfig not implemented")
}
func (*UnimplementedActivityServiceServer) UpdateActivityConfig(ctx context.Context, req *UpdateActivityConfigRequest) (*UpdateActivityConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateActivityConfig not implemented")
}

func RegisterActivityServiceServer(s *grpc.Server, srv ActivityServiceServer) {
	s.RegisterService(&_ActivityService_serviceDesc, srv)
}

func _ActivityService_GetUserActivityProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserActivityProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).GetUserActivityProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activityPb.ActivityService/GetUserActivityProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).GetUserActivityProcess(ctx, req.(*GetUserActivityProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_UpdateUserActivityProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserActivityProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).UpdateUserActivityProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activityPb.ActivityService/UpdateUserActivityProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).UpdateUserActivityProcess(ctx, req.(*UpdateUserActivityProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_GetActivityConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).GetActivityConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activityPb.ActivityService/GetActivityConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).GetActivityConfig(ctx, req.(*GetActivityConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_UpdateActivityConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActivityConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).UpdateActivityConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activityPb.ActivityService/UpdateActivityConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).UpdateActivityConfig(ctx, req.(*UpdateActivityConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ActivityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "activityPb.ActivityService",
	HandlerType: (*ActivityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserActivityProcess",
			Handler:    _ActivityService_GetUserActivityProcess_Handler,
		},
		{
			MethodName: "UpdateUserActivityProcess",
			Handler:    _ActivityService_UpdateUserActivityProcess_Handler,
		},
		{
			MethodName: "GetActivityConfig",
			Handler:    _ActivityService_GetActivityConfig_Handler,
		},
		{
			MethodName: "UpdateActivityConfig",
			Handler:    _ActivityService_UpdateActivityConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity.proto",
}
