// Code generated by protoc-gen-go. DO NOT EDIT.
// source: activity.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PresentPropRequest struct {
	UserId               int32      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PropBlock            *PropBlock `protobuf:"bytes,2,opt,name=prop_block,json=propBlock,proto3" json:"prop_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PresentPropRequest) Reset()         { *m = PresentPropRequest{} }
func (m *PresentPropRequest) String() string { return proto.CompactTextString(m) }
func (*PresentPropRequest) ProtoMessage()    {}
func (*PresentPropRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9da41d51d3e79330, []int{0}
}

func (m *PresentPropRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PresentPropRequest.Unmarshal(m, b)
}
func (m *PresentPropRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PresentPropRequest.Marshal(b, m, deterministic)
}
func (m *PresentPropRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PresentPropRequest.Merge(m, src)
}
func (m *PresentPropRequest) XXX_Size() int {
	return xxx_messageInfo_PresentPropRequest.Size(m)
}
func (m *PresentPropRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PresentPropRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PresentPropRequest proto.InternalMessageInfo

func (m *PresentPropRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PresentPropRequest) GetPropBlock() *PropBlock {
	if m != nil {
		return m.PropBlock
	}
	return nil
}

type PresentPropResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PresentPropResponse) Reset()         { *m = PresentPropResponse{} }
func (m *PresentPropResponse) String() string { return proto.CompactTextString(m) }
func (*PresentPropResponse) ProtoMessage()    {}
func (*PresentPropResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9da41d51d3e79330, []int{1}
}

func (m *PresentPropResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PresentPropResponse.Unmarshal(m, b)
}
func (m *PresentPropResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PresentPropResponse.Marshal(b, m, deterministic)
}
func (m *PresentPropResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PresentPropResponse.Merge(m, src)
}
func (m *PresentPropResponse) XXX_Size() int {
	return xxx_messageInfo_PresentPropResponse.Size(m)
}
func (m *PresentPropResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PresentPropResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PresentPropResponse proto.InternalMessageInfo

func (m *PresentPropResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PresentPropResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type PropBlock struct {
	PropId               int32    `protobuf:"varint,1,opt,name=prop_id,json=propId,proto3" json:"prop_id,omitempty"`
	PropNum              int32    `protobuf:"varint,2,opt,name=prop_num,json=propNum,proto3" json:"prop_num,omitempty"`
	ExpireIn             int32    `protobuf:"varint,3,opt,name=expire_in,json=expireIn,proto3" json:"expire_in,omitempty"`
	PropTitle            string   `protobuf:"bytes,4,opt,name=prop_title,json=propTitle,proto3" json:"prop_title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropBlock) Reset()         { *m = PropBlock{} }
func (m *PropBlock) String() string { return proto.CompactTextString(m) }
func (*PropBlock) ProtoMessage()    {}
func (*PropBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_9da41d51d3e79330, []int{2}
}

func (m *PropBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropBlock.Unmarshal(m, b)
}
func (m *PropBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropBlock.Marshal(b, m, deterministic)
}
func (m *PropBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropBlock.Merge(m, src)
}
func (m *PropBlock) XXX_Size() int {
	return xxx_messageInfo_PropBlock.Size(m)
}
func (m *PropBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_PropBlock.DiscardUnknown(m)
}

var xxx_messageInfo_PropBlock proto.InternalMessageInfo

func (m *PropBlock) GetPropId() int32 {
	if m != nil {
		return m.PropId
	}
	return 0
}

func (m *PropBlock) GetPropNum() int32 {
	if m != nil {
		return m.PropNum
	}
	return 0
}

func (m *PropBlock) GetExpireIn() int32 {
	if m != nil {
		return m.ExpireIn
	}
	return 0
}

func (m *PropBlock) GetPropTitle() string {
	if m != nil {
		return m.PropTitle
	}
	return ""
}

func init() {
	proto.RegisterType((*PresentPropRequest)(nil), "pb.PresentPropRequest")
	proto.RegisterType((*PresentPropResponse)(nil), "pb.PresentPropResponse")
	proto.RegisterType((*PropBlock)(nil), "pb.PropBlock")
}

func init() { proto.RegisterFile("activity.proto", fileDescriptor_9da41d51d3e79330) }

var fileDescriptor_9da41d51d3e79330 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0xd5, 0xa6, 0xcd, 0x14, 0x2f, 0x23, 0xb4, 0xab, 0x22, 0x94, 0x9c, 0x7a, 0x90, 0x1c,
	0xea, 0x1f, 0x10, 0x2f, 0x92, 0x8b, 0x96, 0xd5, 0x9b, 0x87, 0xd0, 0x34, 0x83, 0x2c, 0x36, 0xbb,
	0xeb, 0x7e, 0x88, 0xe0, 0x9f, 0x97, 0xdd, 0xa4, 0x11, 0xf5, 0xb6, 0xef, 0xcd, 0xce, 0x9b, 0xf7,
	0x1e, 0x80, 0x36, 0x4a, 0x17, 0xda, 0x28, 0xa7, 0x70, 0xa4, 0xeb, 0xfc, 0x05, 0x70, 0x63, 0xc8,
	0x92, 0x74, 0x1b, 0xa3, 0x34, 0xa7, 0x77, 0x4f, 0xd6, 0xe1, 0x02, 0x26, 0xde, 0x92, 0xa9, 0x44,
	0xc3, 0x92, 0x65, 0xb2, 0x1a, 0xf3, 0x34, 0xc0, 0xb2, 0xc1, 0xeb, 0x4e, 0xa0, 0xaa, 0xf7, 0x6a,
	0xf7, 0xc6, 0x46, 0xcb, 0x64, 0x35, 0x5b, 0x9f, 0x16, 0xba, 0x2e, 0xc2, 0xf6, 0x5d, 0x20, 0x79,
	0xa6, 0x0f, 0xcf, 0xfc, 0x1e, 0xce, 0x7e, 0x89, 0x5b, 0xad, 0xa4, 0x25, 0x64, 0x30, 0x69, 0xc9,
	0xda, 0xed, 0x2b, 0x45, 0xf5, 0x8c, 0x1f, 0x20, 0xce, 0x21, 0xb5, 0x6e, 0xeb, 0xbc, 0x8d, 0xd2,
	0x63, 0xde, 0xa3, 0xfc, 0x0b, 0xb2, 0xe1, 0x40, 0x30, 0x17, 0x3d, 0xfc, 0x98, 0x0b, 0xb0, 0x6c,
	0xf0, 0x1c, 0xa6, 0x71, 0x20, 0x7d, 0xdb, 0xef, 0xc7, 0x8f, 0x0f, 0xbe, 0xc5, 0x4b, 0xc8, 0xe8,
	0x53, 0x0b, 0x43, 0x95, 0x90, 0xec, 0x38, 0xce, 0xa6, 0x1d, 0x51, 0x4a, 0xbc, 0xea, 0x43, 0x39,
	0xe1, 0xf6, 0xc4, 0x4e, 0xa2, 0xa5, 0x98, 0xe2, 0x39, 0x10, 0xeb, 0x47, 0x98, 0x85, 0xe3, 0x4f,
	0x64, 0x3e, 0xc4, 0x8e, 0xf0, 0x36, 0xc0, 0x21, 0x14, 0xce, 0xbb, 0xf4, 0x7f, 0x2b, 0xbc, 0x58,
	0xfc, 0xe3, 0xbb, 0xf4, 0xf9, 0x51, 0x9d, 0xc6, 0xfa, 0x6f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x9a, 0xb6, 0xe3, 0x12, 0x8c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PropServiceClient is the client API for PropService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PropServiceClient interface {
	// 赠送道具给用户
	PresentProp(ctx context.Context, in *PresentPropRequest, opts ...grpc.CallOption) (*PresentPropResponse, error)
}

type propServiceClient struct {
	cc *grpc.ClientConn
}

func NewPropServiceClient(cc *grpc.ClientConn) PropServiceClient {
	return &propServiceClient{cc}
}

func (c *propServiceClient) PresentProp(ctx context.Context, in *PresentPropRequest, opts ...grpc.CallOption) (*PresentPropResponse, error) {
	out := new(PresentPropResponse)
	err := c.cc.Invoke(ctx, "/pb.PropService/PresentProp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropServiceServer is the server API for PropService service.
type PropServiceServer interface {
	// 赠送道具给用户
	PresentProp(context.Context, *PresentPropRequest) (*PresentPropResponse, error)
}

// UnimplementedPropServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPropServiceServer struct {
}

func (*UnimplementedPropServiceServer) PresentProp(ctx context.Context, req *PresentPropRequest) (*PresentPropResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PresentProp not implemented")
}

func RegisterPropServiceServer(s *grpc.Server, srv PropServiceServer) {
	s.RegisterService(&_PropService_serviceDesc, srv)
}

func _PropService_PresentProp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresentPropRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropServiceServer).PresentProp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PropService/PresentProp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropServiceServer).PresentProp(ctx, req.(*PresentPropRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PropService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PropService",
	HandlerType: (*PropServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PresentProp",
			Handler:    _PropService_PresentProp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity.proto",
}
